<?php

return [
    'years_of_study' => [
        'Year 1',
        'Year 2',
        'Year 3',
        'Year 4',
    ],

    'faculties' => [
        'Communication Media & Broadcasting' => [
            'label' => 'Faculty of Communication Media & Broadcasting',
            'aliases' => [
                'Communication Media & Broadcasting',
                'Faculty of Communication Media & Broadcasting',
                'Faculty of Communication, Media & Broadcasting',
                'Faculty of Communication & Media',
            ],
            'programmes' => [
                'BA (Hons) in Broadcasting and Journalism',
                'BA (Hons) in Professional Communication',
                'BA (Hons) in Digital Film and Television',
                'BA(Hons) in Events Management',
                'Associate Degree in Broadcasting (Radio and Television)',
                'Associate Degree in Journalism and Media',
                'Associate Degree in Public Relations',
                'Associate Degree in Film Production',
                'BA in Digital Film',
                'BA in Human Resource Management',
                'BBuss in Entrepreneurship',
            ],
        ],
        'Communication and Information Technology' => [
            'label' => 'Faculty of Communication and Information Technology',
            'aliases' => [
                'FICT',
                'ICT',
                'Communication and Information Technology',
                'Faculty of Communication and Information Technology',
                'Faculty of Information & Communication Technology',
                'Faculty of Information Technology & Computing',
            ],
            'programmes' => [
                'BSc (Hons) in Information Technology',
                'BSc(Hons) in Business Information Technology',
                'BSc (Hons) in Software Engineering with Multimedia',
                'BSc(Hons) in Electronic Commerce',
                'Associate Degree in Multimedia and Software Engineering',
                'Associate Degree in Business Information Technology',
                'Associate Degree in Information Technology',
                'BSc in Business Information Technology',
            ],
        ],
        'Business Management and Globalization' => [
            'label' => 'Faculty of Business Management and Globalization',
            'aliases' => [
                'Business',
                'Business Management and Globalization',
                'Faculty of Business Management and Globalization',
                'Faculty of Business & Globalization',
                'Faculty of Business & Globalisation',
            ],
            'programmes' => [
                'BBus (Hons) in Entrepreneurship',
                'BA(Hons) in Human Resource Management',
                'BBus (Hons) International Business',
                'Associate Degree in Retail Management',
                'Associate Degree in Business Management',
                'Associate Degree in Marketing',
            ],
        ],
        'Creativity in Tourism and Hospitality' => [
            'label' => 'Faculty of Creativity in Tourism and Hospitality',
            'aliases' => [
                'Hospitality',
                'Tourism',
                'Creativity in Tourism and Hospitality',
                'Faculty of Creativity in Tourism and Hospitality',
                'Faculty of Hospitality & Tourism',
                'Faculty of Hospitality & Tourism Management',
            ],
            'programmes' => [
                'BA (Hons) in Tourism Management',
                'Associate Degree in Hotel Management',
                'Associate Degree in Events Management',
                'Associate Degree in International Tourism',
                'Associate in Tourism Management',
                'Diploma in Hotel Management',
                'BA in Tourism Management',
            ],
        ],
        'Architecture and the Built Environment' => [
            'label' => 'Faculty of Architecture and the Built Environment',
            'aliases' => [
                'Architecture',
                'Architecture and the Built Environment',
                'Faculty of Architecture and the Built Environment',
                'Faculty of Architecture & Built Environment',
                'Faculty of Architecture & The Built Environment',
            ],
            'programmes' => [
                'Bachelor of Interior Architecture',
                'Associate Degree in Architecture Technology',
                'Bachelor of Architectural Studies',
            ],
        ],
        'Design and Innovation - Fashion and Lifestyle Design' => [
            'label' => 'Faculty of Design and Innovation - Faculty of Fashion and Lifestyle Design',
            'aliases' => [
                'Design',
                'Fashion',
                'Design and Innovation',
                'Fashion and Lifestyle Design',
                'Faculty of Design and Innovation',
                'Faculty of Fashion and Lifestyle Design',
                'Faculty of Fashion & Lifestyle Creativity',
            ],
            'programmes' => [
                'BA(Hons) in Fashion and Retailing',
                'BDesign in Professional Design',
                'Associate Degree in Fashion and Apparel Design',
                'Associate Degree in Graphic Design',
                'Associate Degree in Advertising',
                'Associate Degree in Creative Advertising',
                'BA in Fashion and Retailing',
            ],
        ],
    ],
];
